#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "$0")"; pwd)" || exit 2

# Load user configuration
if [[ -f "$BASE_DIR/.env" ]]; then
    source "$BASE_DIR/.env"
fi
TERMINAL_NAME="${TERMINAL_NAME:-Proto-Boy}"

IFS=$'\n'
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

COLUMNS=12


#This function is to display the top header in a centred alignment!
display_center(){
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}


#This string is to be displayed as a custom "title header" at the top, feel free to customise it, as most Terminals in Fallout have their own custom one based on their owner!
greeter="
Personal Terminal \"$TERMINAL_NAME\" Manufactured by RobCo
___________________________________________________"



#Main Menu Screen
mainmenufunc () 
{
clear

#display the Menu text
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
display_center "$BASE_DIR/greeterheader.txt" | pv -qL 80
echo "$greeter" | pv -qL 80
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "SELECT OPTION:" | pv -qL 80

#Display the menu options
echo "1) View Personal Logs"
echo "2) Record Personal Log"
echo "3) Delete Personal Log"
echo "4) Terminate Session"
echo "5) Set Terminal/Inquire"
while true; do
    read -p "#? " menuchoice
    case $menuchoice in
    1)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    viewentriesfunc
    ;;
    2)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    writeentryfunc
    ;;
    3)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    deleteentryfunc
    ;;
    4|exit)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    echo "SESSION TERMINATED" && sleep 1 && exit
    ;;
    5|"")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    echo "ENTERING DIRECT COMMAND MODE. TYPE 'EXIT' TO RETURN." | pv -qL 80
    $SHELL
    repeatmainmenufunc
    ;;
    *)
    play -q $BASE_DIR/ui_hacking_passbad.wav -t alsa
    ;;
    esac
done
}


#Option 1 Menu, Viewing Journal Entries
viewentriesfunc () 
{
#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

#display the Menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "SELECT PERSONAL LOG:" | pv -qL 80
    
    #display the menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    repeatmainmenufunc
    ;;
        *)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    ;;
    esac

    #displays the selected entry
    clear
   display_center "$BASE_DIR/greeterheader.txt"
   echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "$readoption:"  | pv -qL 80
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    cat< "$BASE_DIR/entries/$readoption"  | pv -qL 80
    echo
    read -p "> PRESS ENTER TO RETURN"
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    
    #goes back to main menu
    repeatmainmenufunc
    done
}

#menu for writing an entry
writeentryfunc () 
{

#displays menu text
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "ENTER LOG DESIGNATION:" | pv -qL 80

#reads user input
read entrynameinput 
play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa

#displays menu text again
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "PRESS CTRL+D TO FINALIZE ENTRY" | pv -qL 80
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo $entrynameinput:  | pv -qL 80
echo
#uses cat text editor to write entries. ctrl+d to finish
cat >"$BASE_DIR/entries/$entrynameinput"
cat "$BASE_DIR/entries/$entrynameinput"
clear
play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa

#returns to mainmenu
repeatmainmenufunc


}

#menu to delete an entry
deleteentryfunc () 
{

#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

    #displays menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "SELECT LOG TO DELETE:" | pv -qL 80
    
    #displays menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    repeatmainmenufunc
    ;;
        *)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    ;;
    esac
    
    #displays menu text again
    clear
   display_center "$BASE_DIR/greeterheader.txt"
   echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    echo "CONFIRM DELETION OF $readoption? [Y/N]"  | pv -qL 80
    play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
    
    #detects user input if they typed in "yes". case insensitive as it converts it to all caps
    read confirmdeletion
     if  [[ ${confirmdeletion^^} == "Y" || ${confirmdeletion^^} == "YES" ]]
     then
     rm -f "$BASE_DIR/entries/$readoption"
     play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
     echo "LOG PURGED"
     play -q  $BASE_DIR/ui_hacking_passgood.wav -t alsa
     sleep 0.1
                repeatmainmenufunc
                
            #if something other than yes was typed in
        else
        echo "OPERATION CANCELLED"
        play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
        play -q  $BASE_DIR/ui_hacking_passbad.wav -t alsa 
        sleep 0.2
        
        #goes back to main menu
        repeatmainmenufunc
        fi
        done
}

#same as main menu screen function, but without the annoying animations
repeatmainmenufunc ()
{
clear

display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "SELECT OPTION:" | pv -qL 80
echo "1) View Personal Logs"
echo "2) Record Personal Log"
echo "3) Delete Personal Log"
echo "4) Terminate Session"
echo "5) Set Terminal/Inquire"
while true; do
    read -p "#? " menuchoice
    case $menuchoice in
    1)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    viewentriesfunc
    ;;
    2)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    writeentryfunc
    ;;
    3)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    deleteentryfunc
    ;;
    4|exit)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    echo "SESSION TERMINATED" && sleep 2
    exit
    ;;
    5|"")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav -t alsa
    echo "ENTERING DIRECT COMMAND MODE. TYPE 'exit' TO RETURN." | pv -qL 80
    $SHELL
    repeatmainmenufunc
    ;;
    *)
    play -q $BASE_DIR/ui_hacking_passbad.wav -t alsa
    ;;
    esac
done
}




#some random aesthetic startup junk

clear
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "RBIOS v95.2" | pv -qL 80
read -t 0.4 && mainmenufunc
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "LOADING ROBCO UNIFIED OS..." | pv -qL 80
read -t 0.4 && mainmenufunc
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "64K RAM SYSTEM" | pv -qL 80
read -t 0.4 && mainmenufunc
play -q $BASE_DIR/ui_hacking_charscroll.wav -t alsa
echo "HOLOTAPE READER PRESENT" | pv -qL 80
read -t 0.4 && mainmenufunc
clear
echo $'


  _____       _      _____                   
 |  __ \     | |    / ____|                  
 | |__) |___ | |__ | |     ___               
 |  _  // _ \| \'_ \| |    / _ \              
 | | \ \ (_) | |_) | |___| (_) |             
 |_|__\_\___/|_.__/ \_____\___/  _           

'
           
echo "==============================================" | pv -qL 50
play -q $BASE_DIR/ui_hacking_passgood.wav -t alsa
read -t 1 && mainmenufunc

#goes to the main menu
mainmenufunc;
